apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-michael-deployment
  labels:
    app: hello-world
spec:
  selector:
    matchLabels:
      app: hello-world
  replicas: 2
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - name: hello-world
        image: mhdawson/crud 
        ports:
        - containerPort: 3000
        resources:
          limits:
            memory: 128Mi
            cpu: "500m"
          requests:
            memory: 128Mi
            cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: hello-world
spec:
  selector:
    app: hello-world
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 8080
      nodePort: 30011   
  type: NodePort
